Seccion principal
wolox-training/gz-net-core pull request #6
Opened 2017-07-14 17:32 UTC by gzamudio

# **Summary**
Add index.cshtml.

# **Trello Card**
https://trello.com/c/M1peL2sn

2017-07-14 20:02 UTC, gussiciliano requested changes

2017-07-14 20:02 UTC, gussiciliano commented on MvcMovie.csproj
>  </Project>
add final line

2017-07-14 20:02 UTC, gussiciliano commented on Views/Home/Index.cshtml
> +<link rel='stylesheet' href='~/css/__colors.css' />
add this link in header on shared view

2017-07-14 20:02 UTC, gussiciliano commented on Views/Home/Index.cshtml
> +<link rel='stylesheet' href='~/css/landing.css' />
add this link in header on shared view

2017-07-14 20:02 UTC, gussiciliano commented on Views/Home/Index.cshtml
> +</div>
add final line

2017-07-14 20:02 UTC, gussiciliano commented on Views/Shared/_Layout.cshtml
> +        <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />-->
remove this comment

2017-07-14 20:02 UTC, gussiciliano commented on Views/Shared/_Layout.cshtml
> +        <!--<link rel="stylesheet" href="~/css/site.css" />-->
remove this comment

2017-07-14 20:02 UTC, gussiciliano commented on Views/Shared/_Layout.cshtml
> +        <!--<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
remove this block comment

2017-07-14 20:02 UTC, gussiciliano commented on wwwroot/css/__colors.css
> +$cream-can: #F5C85F;
add final line

2017-07-14 20:02 UTC, gussiciliano commented on wwwroot/css/landing.css
> +body
dont use element for styles, allways use class

2017-07-14 20:02 UTC, gussiciliano commented on wwwroot/css/landing.css
> +    border-top: 8px solid #F5C85F;
use color vas for this

2017-07-14 20:02 UTC, gussiciliano commented on wwwroot/css/landing.css
> +body > div
dont use element for styles, allways use class

2017-07-14 20:02 UTC, gussiciliano commented on wwwroot/css/landing.css
> +img
dont use element for styles, allways use class

2017-07-14 20:02 UTC, gussiciliano commented on wwwroot/css/landing.css
> +}
add final line

2017-07-14 20:02 UTC, gussiciliano commented on wwwroot/css/landing.css
> +{
put this like this
class-name {
.....
}
fix this in all css

2017-07-14 20:02 UTC, gussiciliano commented on wwwroot/css/landing.css
> +    background: -webkit-linear-gradient(top, rgba(245,200, 95, 0), rgba(245,200, 95, 1), rgba(245, 200, 95, 0));
use color vars for this backgrounds

2017-07-17 21:56 UTC, gussiciliano approved these changes

2017-07-17 21:58 UTC, gussiciliano commented on .gitignore
> +node_modules/
add empty line

2017-07-18 19:05 UTC, SKOLZ requested changes
those minor changes and  that's it ;)

2017-07-18 19:05 UTC, SKOLZ commented on wwwroot/css/__colors.css
> +$cream-can: #F5C85F;
this is a SASS type variable, you should add sass for this to work.

2017-07-18 19:05 UTC, SKOLZ commented on wwwroot/css/landing.css
> +body
except for this particular case  you should ALWAYS use classes instead of html tags. move the { to this line leaving a space between the selector and the brace. also use 2 space indentation instead of 4 tabs

2017-07-18 19:05 UTC, SKOLZ commented on assets/styles/landing.scss
> +    font-family: 'Open Sans';
add a default font in case the Open Sans font doesn't load. it should look like this:
```
font-family: 'Open Sans', sans-serif;
```

2017-07-18 19:05 UTC, SKOLZ commented on assets/styles/landing.scss
> +.body .principal {
one of the advantages of sass is selector nesting, use it for this

http://sass-lang.com/guide

2017-07-18 19:05 UTC, SKOLZ commented on assets/styles/landing.scss
> +.body .principal {
also `principal` is the school's director, what you want is `main` for example :P

2017-07-18 23:40 UTC, SKOLZ approved these changes

2017-07-19 13:51 UTC, merged